# Generated by Django 4.2.11 on 2024-07-31 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='name',
            new_name='notes',
        ),
    ]
