# Generated by Django 4.2.11 on 2024-07-31 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_books_delete_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='class_done',
            new_name='readed',
        ),
    ]
